# nginx.conf
pid /tmp/nginx.pid;
worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path /tmp/proxy_temp;
    fastcgi_temp_path /tmp/fastcgi_temp;
    uwsgi_temp_path /tmp/uwsgi_temp;
    scgi_temp_path /tmp/scgi_temp;

    server {
        # Hardcode 8080 to match Cloud Run requirements
        listen 8080; 
        
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            # Use the environment variable here, as Nginx can handle
            # variables in proxy_pass if you define a resolver
            resolver 8.8.8.8; 
            proxy_pass $BACKEND_URL;
            proxy_set_header Host $host;
        }
    }
}