pid /tmp/nginx.pid;
worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path /tmp/proxy_temp;
    fastcgi_temp_path /tmp/fastcgi_temp;
    uwsgi_temp_path /tmp/uwsgi_temp;
    scgi_temp_path /tmp/scgi_temp;

    server {
        # Hardcoded to Cloud Run default
        listen 8080;
        
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            # Replace this URL with your actual backend service URL
            proxy_pass https://settlecan-backend-prod-1064803374828.us-central1.run.app/;
            proxy_set_header Host $host;
        }
    }
}