// taskNotificationRoutes.js — user-facing reads on task_notifications.
// Mounted at /api/v2/notifications (see backend/app.js). Distinct from the
// existing /api/notifications (free-text, admin/community alerts) — this
// one is exclusively task-deadline reminders generated by the scheduler.
const express = require("express");
const router = express.Router();
const { requireAuth } = require("../middleware/authMiddleware");
const controller = require("../controllers/taskNotificationController");

router.use(requireAuth);

router.get("/", controller.list);
router.patch("/:id/read", controller.markRead);

module.exports = router;
